#ifndef LANGUAGE_H
#define LANGUAGE_H

#include <QString>

QString menu_ua[]{"Файл",
                  "Вибір",
                  "Допомога",
                  "Вийти",
                  "Налаштування",
                  "Вибрати всі",
                  "Очистити всі",
                  "Тест для LCD моніторів",
                  "Про програму",
                  "Мова",
                  "Українська",
                  "Англійська"};

QString menu_en[]{"File",
                  "Selection",
                  "Help",
                  "Exit",
                  "Preferences",
                  "Select all",
                  "Clear all",
                  "Test for LCD monitors",
                  "About",
                  "Language",
                  "Ukranian",
                  "English"};

QString buttons_ua[]{"Запустити вибрані тести",
                     "Авто-запуск вибраних тестів",
                     "Калібрувальні тести",
                     "Сіткові тести",
                     "Тести кольором",
                     "Тести на перевірку\nчитабельності"};

QString buttons_en[]{"Run Selected Tests",
                     "Auto Run Selected Tests",
                     "Calibration tests",
                     "Grid tests",
                     "Color tests",
                     "Reading tests"};

QString group_box_ua[]{"Калібрувальні тести",
                       "Тести фокусування",
                       "Чорний фон",
                       "Білий фон",
                       "Суцільні заливки",
                       "Градієнтні заливки",
                       "Палітри кольорів",
                       "Тексти"};

QString group_box_en[]{"Calibration tests",
                       "Focus Tests",
                       "Black background",
                       "White background",
                       "Solid Fills",
                       "Gradient Fills",
                       "Color Palettes",
                       "Texts"};

QString lables_ua[]{"Калібрування РК-дисплея",
                    "Яскравість/контрастність",
                    "Діапазон",
                    "Гамма",
                    "Конвергенція",
                    "Розмір екрану",
                    "Білий візерунок",
                    "Чорний візерунок",
                    "Різкість",
                    "Точки",
                    "Вертикальні лінії",
                    "Горизонтальні лінії",
                    "Біла сітка",
                    "Червона сітка",
                    "Зелена сітка",
                    "Синя сітка",
                    "Пурпурова сітка",
                    "Жовта сітка",
                    "Чорна сітка",
                    "Червона сітка",
                    "Зелена сітка",
                    "Синя сітка",
                    "Пурпурова сітка",
                    "Жовта сітка",
                    "Червоний",
                    "Зелений",
                    "Синій",
                    "Помаранчевий",
                    "Білий",
                    "Чорний",
                    "50% Сірий",
                    "Червоний градієнт",
                    "Зелений градієнт",
                    "Синій градієнт",
                    "Помаранчевий градієнт",
                    "Сірий градієнт",
                    "Палітра кольорів (HSL)",
                    "180 Палітра кольорів (HSL)",
                    "Білий текст на чорному",
                    "Чорний текст на білому",
                    "Червоний текст на синьому",
                    "Синій Текст на зеленому",
                    "Пурпурний Текст на чорному",
                    "Жовтий Текст на синьому"};

QString lables_en[]{"LCD Calibration",
                    "Brightness/Contrast",
                    "Scope",
                    "Gamma",
                    "Convergence",
                    "Screen Size",
                    "White Pattern",
                    "Black Pattern",
                    "Sharpness",
                    "Dots",
                    "Vertical Lines",
                    "Horizontal Lines",
                    "White Grid",
                    "Red Grid",
                    "Green Grid",
                    "Blue Grid",
                    "Magenta Grid",
                    "Yellow Grid",
                    "Black Grid",
                    "Red Grid",
                    "Green Grid",
                    "Blue Grid",
                    "Magenta Grid",
                    "Yellow Grid",
                    "Red",
                    "Green",
                    "Blue",
                    "Orange",
                    "White",
                    "Black",
                    "50% Gray",
                    "Red Gradient",
                    "Green Gradient",
                    "Blue Gradient",
                    "Orange Gradient",
                    "Gray Gradient",
                    "Color Palette (HSL)",
                    "180 Color Palette (HSL)",
                    "White Text on Black",
                    "Black Text on White",
                    "Red Text on Blue",
                    "Blue Text on Green",
                    "Magenta Text on Black",
                    "Yellow Text on Blue"};

QString preferences_ua[]{"Загальні налаштування",
                         "Зберегти стан вибору тесту при виході",
                         "Автоматичний режим",
                         "Секунди, протягом яких буде показано кожен тестовий екран",
                         "Зберегти",
                         "Налаштування збережено",
                         "Налаштування успішно збережено!",
                         "Гаразд"};

QString preferences_en[]{"General settings",
                         "Save test selection state on exit",
                         "Automatic mode",
                         "Seconds that each test screen will be shown",
                         "Save",
                         "Settings Saved",
                         "The settings have been saved!",
                         "Ok"};

QString about_ua[]{"Тестування монітора",
                   " Інформація про продукт:",
                   "    Дана робота виконана в рамках курсового\nпроекту з дисципліни: \"Системне "
                   "програмне забезпечення\"",
                   " Автор роботи:",
                   "    ПІБ, студент групи КІ-3 Національного університету \"Львівська "
                   "політехніка\" спеціальності \"Комп'ютерна інженерія\"",
                   "Версія: 1.0 beta"};

QString about_en[]{"Monitor Testing",
                   " Product information:",
                   "    This work was performed within the scope of the course\nproject in the "
                   "discipline: \"System Software\"",
                   " Author of the work:",
                   "    Name, student of group KI-3 of the National University\n\"Lviv "
                   "Polytechnic\" majoring in Computer Engineering",
                   "Version: 1.0 beta"};

#endif // LANGUAGE_H
